services:
  mysql:
    image: mysql:8.4
    container_name: ecomm-support-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecomm_support
      MYSQL_USER: ecomm_user
      MYSQL_PASSWORD: ecomm_pass

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

    restart: unless-stopped

volumes:
  mysql_data: